GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py:386: LightningDeprecationWarning: The `Callback.on_epoch_end` hook was deprecated in v1.6 and will be removed in v1.8. Please use `Callback.on_<train/validation/test>_epoch_end` instead.
  f"The `Callback.{hook}` hook was deprecated in v1.6 and"
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main(args)
  File "train.py", line 299, in main
    dm.val_dataloader(),
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pl_bolts/models/autoencoders/basic_ae/basic_ae_module.py", line 122, in validation_step
    loss, logs = self.step(batch, batch_idx)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pl_bolts/models/autoencoders/basic_ae/basic_ae_module.py", line 112, in step
    loss = F.mse_loss(x_hat, x, reduction="mean")
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/nn/functional.py", line 3111, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/functional.py", line 72, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (8) must match the size of tensor b (15) at non-singleton dimension 3
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main(args)
  File "train.py", line 299, in main
    dm.val_dataloader(),
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pl_bolts/models/autoencoders/basic_ae/basic_ae_module.py", line 122, in validation_step
    loss, logs = self.step(batch, batch_idx)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pl_bolts/models/autoencoders/basic_ae/basic_ae_module.py", line 112, in step
    loss = F.mse_loss(x_hat, x, reduction="mean")
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/nn/functional.py", line 3111, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/functional.py", line 72, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (8) must match the size of tensor b (15) at non-singleton dimension 3
┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃[1m   [22m┃[1m Name    [22m┃[1m Type          [22m┃[1m Params [22m┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ encoder │ ResNetEncoder │ 11.2 M │
│ 1 │ decoder │ ResNetDecoder │  8.6 M │
│ 2 │ fc      │ Linear        │  131 K │
└───┴─────────┴───────────────┴────────┘
[1mTrainable params[22m: 19.9 M
[1mNon-trainable params[22m: 0
[1mTotal params[22m: 19.9 M
[1mTotal estimated model params size (MB)[22m: 79
